dist: bionic
language: python
python: 3.8

cache:
  - pip

if: commit_message =~ /(\[BUILD\]|\[TEST\])/

install:
  - pip install pipenv
  - pipenv install

script:
  - ./manage.py makemigrations
  - ./manage.py migrate
  - ./manage.py compilemessages
  - ./manage.py collectstatic --no-input
  - ./manage.py compress --force
  - ./population_script.py || exit 3
  - ./manage.py test
