# Generated by Django 3.0.5 on 2020-04-05 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BoardTask',
        ),
    ]
