# Generated by Django 3.0.5 on 2020-04-03 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_auto_20200402_2208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_belongs_to_group',
            name='group',
        ),
        migrations.RemoveField(
            model_name='user_belongs_to_group',
            name='user',
        ),
        migrations.DeleteModel(
            name='group',
        ),
        migrations.DeleteModel(
            name='User_belongs_to_group',
        ),
    ]
