# Generated by Django 3.0.5 on 2020-04-03 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0004_auto_20200403_0549'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='board_id',
            new_name='id',
        ),
    ]
